Changed workflow

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -48,7 +48,7 @@ jobs:
           git checkout -- package.json
 
           HIGHEST_VERSION=$(echo -e "$CURRENT_VERSION\n$MAIN_VERSION" | sort -V | tail -n1)
-          
+
           if [ "$CURRENT_VERSION" = "$MAIN_VERSION" ]; then
             echo "Error: Version in package.json ($CURRENT_VERSION) has not been incremented compared to main branch ($MAIN_VERSION)."
             exit 1
@@ -59,18 +59,16 @@ jobs:
             echo "Version in package.json ($CURRENT_VERSION) is higher than on the main branch ($MAIN_VERSION)."
             fi
 
-
   check-changelog:
-      runs-on: ubuntu-latest
-      needs: check-version
-      steps:
-        - uses: actions/checkout@v4
-        - name: Check if CHANGELOG.md has been updated
-          run: |
-            if ! grep -qE "## \[?$VERSION_IN_PACKAGE_JSON\]?" CHANGELOG.md; then
-            echo "Error: CHANGELOG.md has not been updated for version $VERSION_IN_PACKAGE_JSON."
-            exit 1
-            else
-            echo "CHANGELOG.md has been updated for version $VERSION_IN_PACKAGE_JSON."
-            fi
-
+    runs-on: ubuntu-latest
+    needs: check-version
+    steps:
+      - uses: actions/checkout@v4
+      - name: Check if CHANGELOG.md has been updated
+        run: |
+          if ! grep -qE "## \[?$VERSION_IN_PACKAGE_JSON\]?" CHANGELOG.md; then
+          echo "Error: CHANGELOG.md has not been updated for version $VERSION_IN_PACKAGE_JSON."
+          exit 1
+          else
+          echo "CHANGELOG.md has been updated for version $VERSION_IN_PACKAGE_JSON."
+          fi
