Changed workflow

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -49,26 +49,28 @@ jobs:
 
           HIGHEST_VERSION=$(echo -e "$CURRENT_VERSION\n$MAIN_VERSION" | sort -V | tail -n1)
           
-          if [ "$HIGHEST_VERSION" != "$CURRENT_VERSION" ]; then
+          if [ "$CURRENT_VERSION" = "$MAIN_VERSION" ]; then
             echo "Error: Version in package.json ($CURRENT_VERSION) has not been incremented compared to main branch ($MAIN_VERSION)."
             exit 1
-          else
+            elif [ "$HIGHEST_VERSION" != "$CURRENT_VERSION" ]; then
+          echo "Error: Version in package.json ($CURRENT_VERSION) is not the highest compared to main branch ($MAIN_VERSION)."
+            exit 1
+            else
             echo "Version in package.json ($CURRENT_VERSION) is higher than on the main branch ($MAIN_VERSION)."
-          fi
+            fi
+
 
   check-changelog:
-    runs-on: ubuntu-latest
-    needs: check-version
-    steps:
-      - uses: actions/checkout@v4
-      - name: Check if CHANGELOG.md has been updated
-        run: |
-          VERSION_IN_PACKAGE_JSON=$(node -p "require('./package.json').version")
-
-          # Перевіряємо, чи файл CHANGELOG.md містить запис про нову версію
-          if grep -q "## $VERSION_IN_PACKAGE_JSON" CHANGELOG.md; then
-            echo "CHANGELOG.md has been updated for version $VERSION_IN_PACKAGE_JSON."
-          else
+      runs-on: ubuntu-latest
+      needs: check-version
+      steps:
+        - uses: actions/checkout@v4
+        - name: Check if CHANGELOG.md has been updated
+          run: |
+            if ! grep -qE "## \[?$VERSION_IN_PACKAGE_JSON\]?" CHANGELOG.md; then
             echo "Error: CHANGELOG.md has not been updated for version $VERSION_IN_PACKAGE_JSON."
             exit 1
-          fi
+            else
+            echo "CHANGELOG.md has been updated for version $VERSION_IN_PACKAGE_JSON."
+            fi
+
