Changed version

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -37,23 +37,27 @@ jobs:
         uses: actions/setup-node@v4
         with:
           node-version: '20.x'
-      - name: Check if version has been incremented compared to the main branch
+      - name: Check if version has been incremented compared to main branch
         run: |
           CURRENT_VERSION=$(node -p "require('./package.json').version")
+
           git fetch origin main
           git checkout origin/main -- package.json
           MAIN_VERSION=$(node -p "require('./package.json').version")
+
           git checkout -- package.json
 
-          echo "Current Version: $CURRENT_VERSION"
-          echo "Main Branch Version: $MAIN_VERSION"
+          HIGHEST_VERSION=$(echo -e "$CURRENT_VERSION\n$MAIN_VERSION" | sort -V | tail -n1)
 
-          if [ "$(printf '%s\n' "$CURRENT_VERSION" "$MAIN_VERSION" | sort -V | tail -n 1)" != "$CURRENT_VERSION" ]; then
-            echo "Error: Version in package.json ($CURRENT_VERSION) is not higher than on the main branch ($MAIN_VERSION)."
+          if [ "$CURRENT_VERSION" = "$MAIN_VERSION" ]; then
+            echo "Error: Version in package.json ($CURRENT_VERSION) has not been incremented compared to main branch ($MAIN_VERSION)."
             exit 1
-          else
+            elif [ "$HIGHEST_VERSION" != "$CURRENT_VERSION" ]; then
+          echo "Error: Version in package.json ($CURRENT_VERSION) is not the highest compared to main branch ($MAIN_VERSION)."
+            exit 1
+            else
             echo "Version in package.json ($CURRENT_VERSION) is higher than on the main branch ($MAIN_VERSION)."
-          fi
+            fi
 
   check-changelog:
     runs-on: ubuntu-latest
