Fixed check version workflow

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -7,6 +7,49 @@ on:
     types: [opened, synchronize, reopened]
 
 jobs:
+  check-version:
+    runs-on: ubuntu-latest
+    needs: validation
+    steps:
+      - uses: actions/checkout@v4
+      - name: Setup Node.js
+        uses: actions/setup-node@v4
+        with:
+          node-version: '20.x'
+      - name: Install compare-versions
+        run: npm install compare-versions
+      - name: Check if version has been incremented compared to main branch
+        run: |
+          CURRENT_VERSION=$(node -p "require('./package.json').version")
+          git fetch origin main
+          git checkout origin/main -- package.json
+          MAIN_VERSION=$(node -p "require('./package.json').version")
+          git checkout -- package.json
+
+          VERSION_COMPARISON=$(node -e "const compareVersions = require('compare-versions'); console.log(compareVersions('$CURRENT_VERSION', '$MAIN_VERSION'))")
+
+          if [ "$VERSION_COMPARISON" -gt 0 ]; then
+            echo "Version in package.json ($CURRENT_VERSION) is higher than on the main branch ($MAIN_VERSION)."
+          else
+            echo "Error: Version in package.json ($CURRENT_VERSION) is not higher than on the main branch ($MAIN_VERSION)."
+            exit 1
+          fi
+
+  check-changelog:
+    runs-on: ubuntu-latest
+    needs: check-version
+    steps:
+      - uses: actions/checkout@v4
+      - name: Check if CHANGELOG.md has been updated
+        run: |
+          VERSION_IN_PACKAGE_JSON=$(node -p "require('./package.json').version")
+
+          if ! grep -qE "## \[?$VERSION_IN_PACKAGE_JSON\]?" CHANGELOG.md; then
+            echo "Error: CHANGELOG.md has not been updated for version $VERSION_IN_PACKAGE_JSON."
+            exit 1
+          else
+            echo "CHANGELOG.md has been updated for version $VERSION_IN_PACKAGE_JSON."
+          fi
   validation:
     runs-on: ubuntu-latest
     strategy:
@@ -27,47 +70,3 @@ jobs:
         run: npm run lint:check
       - name: Run tests with coverage
         run: npm test -- --coverage
-
-  check-version:
-    runs-on: ubuntu-latest
-    needs: validation
-    steps:
-      - uses: actions/checkout@v4
-      - name: Setup Node.js
-        uses: actions/setup-node@v4
-        with:
-          node-version: '20.x'
-      - name: Install compare-versions
-        run: npm install compare-versions
-      - name: Check if version has been incremented compared to main branch
-        run: |
-          CURRENT_VERSION=$(node -p "require('./package.json').version")
-          git fetch origin main
-          git checkout origin/main -- package.json
-          MAIN_VERSION=$(node -p "require('./package.json').version")
-          git checkout -- package.json
-
-          VERSION_COMPARISON=$(node -p "const compareVersions = require('compare-versions'); compareVersions('$CURRENT_VERSION', '$MAIN_VERSION')")
-
-          if [ "$VERSION_COMPARISON" -gt 0 ]; then
-            echo "Version in package.json ($CURRENT_VERSION) is higher than on the main branch ($MAIN_VERSION)."
-          else
-            echo "Error: Version in package.json ($CURRENT_VERSION) is not higher than on the main branch ($MAIN_VERSION)."
-            exit 1
-          fi
-
-  check-changelog:
-    runs-on: ubuntu-latest
-    needs: check-version
-    steps:
-      - uses: actions/checkout@v4
-      - name: Check if CHANGELOG.md has been updated
-        run: |
-          VERSION_IN_PACKAGE_JSON=$(node -p "require('./package.json').version")
-
-          if ! grep -qE "## \[?$VERSION_IN_PACKAGE_JSON\]?" CHANGELOG.md; then
-          echo "Error: CHANGELOG.md has not been updated for version $VERSION_IN_PACKAGE_JSON."
-          exit 1
-          else
-          echo "CHANGELOG.md has been updated for version $VERSION_IN_PACKAGE_JSON."
-          fi
