Fixed check version workflow

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -40,23 +40,16 @@ jobs:
       - name: Check if version has been incremented compared to main branch
         run: |
           CURRENT_VERSION=$(node -p "require('./package.json').version")
-
           git fetch origin main
           git checkout origin/main -- package.json
           MAIN_VERSION=$(node -p "require('./package.json').version")
-
           git checkout -- package.json
-
-          VERSION_COMPARISON=$(npm version $CURRENT_VERSION --allow-same-version > /dev/null; npm version $MAIN_VERSION --allow-same-version > /dev/null; npm version | grep -A 1 $MAIN_VERSION | tail -n 1)
-
-          if [ "$CURRENT_VERSION" = "$MAIN_VERSION" ]; then
-            echo "Error: Version in package.json ($CURRENT_VERSION) has not been incremented compared to main branch ($MAIN_VERSION)."
-            exit 1
-          elif [ "$VERSION_COMPARISON" != "$CURRENT_VERSION" ]; then
-            echo "Error: Version in package.json ($CURRENT_VERSION) is not the highest compared to main branch ($MAIN_VERSION)."
-            exit 1
-          else
+          
+          if [ "$(printf '%s\n' "$CURRENT_VERSION" "$MAIN_VERSION" | sort -V | head -n1)" = "$MAIN_VERSION" ] && [ "$CURRENT_VERSION" != "$MAIN_VERSION" ]; then
             echo "Version in package.json ($CURRENT_VERSION) is higher than on the main branch ($MAIN_VERSION)."
+          else
+            echo "Error: Version in package.json ($CURRENT_VERSION) is not higher than on the main branch ($MAIN_VERSION)."
+            exit 1
           fi
 
   check-changelog:
